#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SMSSDKSample.Resource", IsApplication=true)]

namespace SMSSDKSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int smssdk_country_group_a = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int smssdk_country_group_b = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int smssdk_country_group_c = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int smssdk_country_group_d = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int smssdk_country_group_e = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int smssdk_country_group_f = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int smssdk_country_group_g = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int smssdk_country_group_h = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int smssdk_country_group_i = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int smssdk_country_group_j = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int smssdk_country_group_k = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int smssdk_country_group_l = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int smssdk_country_group_m = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int smssdk_country_group_n = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int smssdk_country_group_o = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int smssdk_country_group_p = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int smssdk_country_group_q = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int smssdk_country_group_r = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int smssdk_country_group_s = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int smssdk_country_group_t = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int smssdk_country_group_u = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int smssdk_country_group_v = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int smssdk_country_group_w = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int smssdk_country_group_x = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int smssdk_country_group_y = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int smssdk_country_group_z = 2131034137;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int smssdk_black = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int smssdk_gray = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int smssdk_gray_press = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int smssdk_lv_item_divider = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int smssdk_lv_item_selector = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int smssdk_lv_title_color = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int smssdk_lv_tv_color = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int smssdk_transparent = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int smssdk_white = 2131165192;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int smssdk_back_arrow = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int smssdk_back_arrow2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int smssdk_btn_disenable = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int smssdk_btn_enable = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int smssdk_circular_bg = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int smssdk_cl_divider = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int smssdk_clear_search = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int smssdk_corners_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int smssdk_corners_bg_nor = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int smssdk_corners_bg_pre = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int smssdk_country_bg_selector = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int smssdk_country_group_scroll_down = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int smssdk_country_group_scroll_up = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int smssdk_cp_default_avatar = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int smssdk_default_avatar = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int smssdk_dialog_back = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int smssdk_dialog_bg = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int smssdk_dialog_btn_back = 2130837523;
			
			// aapt resource value: 0x7f02001b
			public const int smssdk_dialog_btn_nor = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int smssdk_dialog_btn_pre = 2130837532;
			
			// aapt resource value: 0x7f020014
			public const int smssdk_edittext_bg_selector = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int smssdk_input_bg_focus = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int smssdk_input_bg_normal = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int smssdk_input_bg_special_focus = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int smssdk_input_bg_special_normal = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int smssdk_search_icon = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int smssdk_sharesdk_icon = 2130837530;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090001
			public const int btn_bind_phone = 2131296257;
			
			// aapt resource value: 0x7f090008
			public const int btn_dialog_cancel = 2131296264;
			
			// aapt resource value: 0x7f090007
			public const int btn_dialog_ok = 2131296263;
			
			// aapt resource value: 0x7f090005
			public const int et_appkey = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int et_appsecret = 2131296262;
			
			// aapt resource value: 0x7f090002
			public const int rl_contact = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int tv_contact = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int tv_num = 2131296260;
			
			// aapt resource value: 0x7f090000
			public const int tv_title = 2131296256;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int main_activity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int smssdk_set_appkey_dialog = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int smssdk_pydb = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0600a2
			public const int app_name = 2131099810;
			
			// aapt resource value: 0x7f060073
			public const int smssdk_add_contact = 2131099763;
			
			// aapt resource value: 0x7f0600a6
			public const int smssdk_appkey = 2131099814;
			
			// aapt resource value: 0x7f0600a5
			public const int smssdk_appkey_dialog_title = 2131099813;
			
			// aapt resource value: 0x7f0600a7
			public const int smssdk_appkey_hint = 2131099815;
			
			// aapt resource value: 0x7f0600a8
			public const int smssdk_appsecret = 2131099816;
			
			// aapt resource value: 0x7f0600a9
			public const int smssdk_appsecrethint = 2131099817;
			
			// aapt resource value: 0x7f060074
			public const int smssdk_back = 2131099764;
			
			// aapt resource value: 0x7f0600a3
			public const int smssdk_bind_mobile_show = 2131099811;
			
			// aapt resource value: 0x7f060075
			public const int smssdk_cancel = 2131099765;
			
			// aapt resource value: 0x7f060076
			public const int smssdk_choice_invite_phones = 2131099766;
			
			// aapt resource value: 0x7f060077
			public const int smssdk_choose_country = 2131099767;
			
			// aapt resource value: 0x7f060078
			public const int smssdk_close_identify_page_dialog = 2131099768;
			
			// aapt resource value: 0x7f0600a4
			public const int smssdk_contact = 2131099812;
			
			// aapt resource value: 0x7f060079
			public const int smssdk_contacts_detail = 2131099769;
			
			// aapt resource value: 0x7f06007a
			public const int smssdk_contacts_in_app = 2131099770;
			
			// aapt resource value: 0x7f06007b
			public const int smssdk_contacts_out_app = 2131099771;
			
			// aapt resource value: 0x7f06007c
			public const int smssdk_contacts_phones = 2131099772;
			
			// aapt resource value: 0x7f06007d
			public const int smssdk_country = 2131099773;
			
			// aapt resource value: 0x7f06007e
			public const int smssdk_country_not_support_currently = 2131099774;
			
			// aapt resource value: 0x7f060000
			public const int smssdk_error_desc_400 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int smssdk_error_desc_401 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int smssdk_error_desc_402 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int smssdk_error_desc_403 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int smssdk_error_desc_404 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int smssdk_error_desc_405 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int smssdk_error_desc_406 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int smssdk_error_desc_407 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int smssdk_error_desc_408 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int smssdk_error_desc_418 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int smssdk_error_desc_419 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int smssdk_error_desc_450 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int smssdk_error_desc_451 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int smssdk_error_desc_452 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int smssdk_error_desc_453 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int smssdk_error_desc_454 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int smssdk_error_desc_455 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int smssdk_error_desc_456 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int smssdk_error_desc_457 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int smssdk_error_desc_458 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int smssdk_error_desc_459 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int smssdk_error_desc_460 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int smssdk_error_desc_461 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int smssdk_error_desc_462 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int smssdk_error_desc_463 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int smssdk_error_desc_464 = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int smssdk_error_desc_465 = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int smssdk_error_desc_466 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int smssdk_error_desc_467 = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int smssdk_error_desc_468 = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int smssdk_error_desc_469 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int smssdk_error_desc_470 = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int smssdk_error_desc_471 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int smssdk_error_desc_472 = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int smssdk_error_desc_473 = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int smssdk_error_desc_474 = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int smssdk_error_desc_475 = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int smssdk_error_desc_476 = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int smssdk_error_desc_477 = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int smssdk_error_desc_478 = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int smssdk_error_desc_500 = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int smssdk_error_desc_501 = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int smssdk_error_desc_502 = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int smssdk_error_desc_503 = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int smssdk_error_desc_504 = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int smssdk_error_desc_505 = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int smssdk_error_desc_506 = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int smssdk_error_desc_507 = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int smssdk_error_desc_508 = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int smssdk_error_desc_510 = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int smssdk_error_desc_511 = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int smssdk_error_desc_600 = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int smssdk_error_desc_601 = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int smssdk_error_desc_602 = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int smssdk_error_desc_603 = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int smssdk_error_desc_604 = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int smssdk_error_desc_605 = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int smssdk_error_desc_server_busy = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int smssdk_error_detail_400 = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int smssdk_error_detail_401 = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int smssdk_error_detail_402 = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int smssdk_error_detail_403 = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int smssdk_error_detail_404 = 2131099710;
			
			// aapt resource value: 0x7f06003f
			public const int smssdk_error_detail_405 = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int smssdk_error_detail_406 = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int smssdk_error_detail_407 = 2131099713;
			
			// aapt resource value: 0x7f060042
			public const int smssdk_error_detail_408 = 2131099714;
			
			// aapt resource value: 0x7f060043
			public const int smssdk_error_detail_418 = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int smssdk_error_detail_419 = 2131099716;
			
			// aapt resource value: 0x7f060045
			public const int smssdk_error_detail_450 = 2131099717;
			
			// aapt resource value: 0x7f060046
			public const int smssdk_error_detail_451 = 2131099718;
			
			// aapt resource value: 0x7f060047
			public const int smssdk_error_detail_452 = 2131099719;
			
			// aapt resource value: 0x7f060048
			public const int smssdk_error_detail_453 = 2131099720;
			
			// aapt resource value: 0x7f060049
			public const int smssdk_error_detail_454 = 2131099721;
			
			// aapt resource value: 0x7f06004a
			public const int smssdk_error_detail_455 = 2131099722;
			
			// aapt resource value: 0x7f06004b
			public const int smssdk_error_detail_456 = 2131099723;
			
			// aapt resource value: 0x7f06004c
			public const int smssdk_error_detail_457 = 2131099724;
			
			// aapt resource value: 0x7f06004d
			public const int smssdk_error_detail_458 = 2131099725;
			
			// aapt resource value: 0x7f06004e
			public const int smssdk_error_detail_459 = 2131099726;
			
			// aapt resource value: 0x7f06004f
			public const int smssdk_error_detail_460 = 2131099727;
			
			// aapt resource value: 0x7f060050
			public const int smssdk_error_detail_461 = 2131099728;
			
			// aapt resource value: 0x7f060051
			public const int smssdk_error_detail_462 = 2131099729;
			
			// aapt resource value: 0x7f060052
			public const int smssdk_error_detail_463 = 2131099730;
			
			// aapt resource value: 0x7f060053
			public const int smssdk_error_detail_464 = 2131099731;
			
			// aapt resource value: 0x7f060054
			public const int smssdk_error_detail_465 = 2131099732;
			
			// aapt resource value: 0x7f060055
			public const int smssdk_error_detail_466 = 2131099733;
			
			// aapt resource value: 0x7f060056
			public const int smssdk_error_detail_467 = 2131099734;
			
			// aapt resource value: 0x7f060057
			public const int smssdk_error_detail_468 = 2131099735;
			
			// aapt resource value: 0x7f060058
			public const int smssdk_error_detail_469 = 2131099736;
			
			// aapt resource value: 0x7f060059
			public const int smssdk_error_detail_470 = 2131099737;
			
			// aapt resource value: 0x7f06005a
			public const int smssdk_error_detail_471 = 2131099738;
			
			// aapt resource value: 0x7f06005b
			public const int smssdk_error_detail_472 = 2131099739;
			
			// aapt resource value: 0x7f06005c
			public const int smssdk_error_detail_473 = 2131099740;
			
			// aapt resource value: 0x7f06005d
			public const int smssdk_error_detail_474 = 2131099741;
			
			// aapt resource value: 0x7f06005e
			public const int smssdk_error_detail_475 = 2131099742;
			
			// aapt resource value: 0x7f06005f
			public const int smssdk_error_detail_476 = 2131099743;
			
			// aapt resource value: 0x7f060060
			public const int smssdk_error_detail_477 = 2131099744;
			
			// aapt resource value: 0x7f060061
			public const int smssdk_error_detail_478 = 2131099745;
			
			// aapt resource value: 0x7f060062
			public const int smssdk_error_detail_500 = 2131099746;
			
			// aapt resource value: 0x7f060063
			public const int smssdk_error_detail_501 = 2131099747;
			
			// aapt resource value: 0x7f060064
			public const int smssdk_error_detail_502 = 2131099748;
			
			// aapt resource value: 0x7f060065
			public const int smssdk_error_detail_503 = 2131099749;
			
			// aapt resource value: 0x7f060066
			public const int smssdk_error_detail_504 = 2131099750;
			
			// aapt resource value: 0x7f060067
			public const int smssdk_error_detail_505 = 2131099751;
			
			// aapt resource value: 0x7f060068
			public const int smssdk_error_detail_506 = 2131099752;
			
			// aapt resource value: 0x7f060069
			public const int smssdk_error_detail_507 = 2131099753;
			
			// aapt resource value: 0x7f06006a
			public const int smssdk_error_detail_508 = 2131099754;
			
			// aapt resource value: 0x7f06006b
			public const int smssdk_error_detail_510 = 2131099755;
			
			// aapt resource value: 0x7f06006c
			public const int smssdk_error_detail_511 = 2131099756;
			
			// aapt resource value: 0x7f06006d
			public const int smssdk_error_detail_600 = 2131099757;
			
			// aapt resource value: 0x7f06006e
			public const int smssdk_error_detail_601 = 2131099758;
			
			// aapt resource value: 0x7f06006f
			public const int smssdk_error_detail_602 = 2131099759;
			
			// aapt resource value: 0x7f060070
			public const int smssdk_error_detail_603 = 2131099760;
			
			// aapt resource value: 0x7f060071
			public const int smssdk_error_detail_604 = 2131099761;
			
			// aapt resource value: 0x7f060072
			public const int smssdk_error_detail_605 = 2131099762;
			
			// aapt resource value: 0x7f06007f
			public const int smssdk_get_phone_verifycode_today_frequentlly = 2131099775;
			
			// aapt resource value: 0x7f060080
			public const int smssdk_get_verifycode_frequentlly = 2131099776;
			
			// aapt resource value: 0x7f060081
			public const int smssdk_identify_code = 2131099777;
			
			// aapt resource value: 0x7f060082
			public const int smssdk_invite = 2131099778;
			
			// aapt resource value: 0x7f060083
			public const int smssdk_invite_content = 2131099779;
			
			// aapt resource value: 0x7f060084
			public const int smssdk_make_sure_country_mobile = 2131099780;
			
			// aapt resource value: 0x7f060085
			public const int smssdk_make_sure_mobile_detail = 2131099781;
			
			// aapt resource value: 0x7f060086
			public const int smssdk_make_sure_mobile_num = 2131099782;
			
			// aapt resource value: 0x7f060087
			public const int smssdk_make_sure_send_sounds = 2131099783;
			
			// aapt resource value: 0x7f060088
			public const int smssdk_network_error = 2131099784;
			
			// aapt resource value: 0x7f060089
			public const int smssdk_next = 2131099785;
			
			// aapt resource value: 0x7f06008a
			public const int smssdk_not_invite = 2131099786;
			
			// aapt resource value: 0x7f06008b
			public const int smssdk_ok = 2131099787;
			
			// aapt resource value: 0x7f06008c
			public const int smssdk_receive_msg = 2131099788;
			
			// aapt resource value: 0x7f06008d
			public const int smssdk_regist = 2131099789;
			
			// aapt resource value: 0x7f06008e
			public const int smssdk_resend_identify_code = 2131099790;
			
			// aapt resource value: 0x7f06008f
			public const int smssdk_search = 2131099791;
			
			// aapt resource value: 0x7f060090
			public const int smssdk_search_contact = 2131099792;
			
			// aapt resource value: 0x7f060091
			public const int smssdk_send_invitation = 2131099793;
			
			// aapt resource value: 0x7f060092
			public const int smssdk_send_mobile_detail = 2131099794;
			
			// aapt resource value: 0x7f060093
			public const int smssdk_send_sounds = 2131099795;
			
			// aapt resource value: 0x7f060094
			public const int smssdk_send_sounds_identify_code = 2131099796;
			
			// aapt resource value: 0x7f060095
			public const int smssdk_send_sounds_success = 2131099797;
			
			// aapt resource value: 0x7f060096
			public const int smssdk_smart_verify_already = 2131099798;
			
			// aapt resource value: 0x7f060097
			public const int smssdk_smart_verify_tips = 2131099799;
			
			// aapt resource value: 0x7f060098
			public const int smssdk_submit = 2131099800;
			
			// aapt resource value: 0x7f060099
			public const int smssdk_unreceive_identify_code = 2131099801;
			
			// aapt resource value: 0x7f06009a
			public const int smssdk_user_info_submited = 2131099802;
			
			// aapt resource value: 0x7f06009b
			public const int smssdk_virificaition_code_sent = 2131099803;
			
			// aapt resource value: 0x7f06009c
			public const int smssdk_virificaition_code_wrong = 2131099804;
			
			// aapt resource value: 0x7f06009d
			public const int smssdk_wait = 2131099805;
			
			// aapt resource value: 0x7f06009e
			public const int smssdk_write_identify_code = 2131099806;
			
			// aapt resource value: 0x7f06009f
			public const int smssdk_write_mobile_phone = 2131099807;
			
			// aapt resource value: 0x7f0600a0
			public const int smssdk_write_right_mobile_phone = 2131099808;
			
			// aapt resource value: 0x7f0600a1
			public const int smssdk_your_ccount_is_verified = 2131099809;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int AppTheme = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int CommonDialog = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
